apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gate
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 defaultBackend:
         service:
              name: php
              port:
                 number: 80
 rules:
  - host: karkuvel.com 
    http:
      paths:
      - path: /eureka
        pathType: Prefix
        backend:
           service:
             name: php
             port:
                number: 80
